insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2010, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2010, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2010, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2010, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2010, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2010, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2010, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2010, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2010, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2010, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2010, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2010, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2010, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2010, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2010, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2010, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2010, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2010, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2010, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2010, 'BELFORT', 'POLIGNY');
