insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2005, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2005, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2005, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2005, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2005, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2005, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2005, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2005, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2005, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2005, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2005, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2005, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2005, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2005, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2005, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2005, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2005, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2005, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2005, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2005, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2006, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2006, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2006, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2006, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2006, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2006, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2006, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2006, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2006, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2006, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2006, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2006, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2006, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2006, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2006, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2006, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2006, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2006, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2006, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2006, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2007, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2007, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2007, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2007, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2007, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2007, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2007, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2007, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2007, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2007, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2007, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2007, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2007, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2007, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2007, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2007, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2007, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2007, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2007, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2007, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2008, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2008, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2008, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2008, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2008, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2008, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2008, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2008, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2008, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2008, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2008, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2008, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2008, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2008, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2008, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2008, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2008, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2008, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2008, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2008, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2009, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2009, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2009, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2009, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2009, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2009, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2009, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2009, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2009, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2009, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2009, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2009, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2009, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2009, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2009, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2009, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2009, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2009, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2009, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2009, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2010, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2010, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2010, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2010, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2010, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2010, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2010, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2010, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2010, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2010, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2010, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2010, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2010, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2010, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2010, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2010, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2010, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2010, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2010, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2010, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2011, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2011, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2011, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2011, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2011, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2011, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2011, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2011, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2011, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2011, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2011, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2011, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2011, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2011, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2011, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2011, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2011, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2011, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2011, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2011, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2012, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2012, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2012, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2012, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2012, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2012, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2012, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2012, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2012, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2012, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2012, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2012, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2012, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2012, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2012, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2012, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2012, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2012, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2012, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2012, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2013, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2013, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2013, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2013, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2013, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2013, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2013, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2013, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2013, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2013, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2013, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2013, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2013, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2013, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2013, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2013, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2013, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2013, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2013, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2013, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2014, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2014, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2014, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2014, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2014, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2014, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2014, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2014, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2014, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2014, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2014, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2014, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2014, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2014, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2014, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2014, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2014, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2014, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2014, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2014, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2015, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2015, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2015, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2015, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2015, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2015, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2015, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2015, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2015, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2015, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2015, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2015, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2015, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2015, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2015, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2015, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2015, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2015, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2015, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2015, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2016, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2016, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2016, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2016, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2016, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2016, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2016, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2016, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2016, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2016, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2016, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2016, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2016, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2016, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2016, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2016, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2016, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2016, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2016, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2016, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2017, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2017, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2017, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2017, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2017, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2017, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2017, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2017, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2017, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2017, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2017, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2017, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2017, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2017, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2017, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2017, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2017, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2017, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2017, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2017, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2018, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2018, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2018, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2018, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2018, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2018, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2018, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2018, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2018, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2018, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2018, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2018, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2018, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2018, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2018, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2018, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2018, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2018, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2018, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2018, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2019, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2019, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2019, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2019, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2019, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2019, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2019, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2019, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2019, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2019, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2019, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2019, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2019, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2019, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2019, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2019, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2019, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2019, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2019, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2019, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2020, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2020, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2020, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2020, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2020, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2020, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2020, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2020, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2020, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2020, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2020, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2020, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2020, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2020, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2020, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2020, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2020, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2020, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2020, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2020, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2021, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2021, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2021, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2021, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2021, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2021, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2021, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2021, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2021, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2021, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2021, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2021, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2021, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2021, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2021, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2021, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2021, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2021, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2021, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2021, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2022, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2022, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2022, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2022, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2022, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2022, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2022, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2022, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2022, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2022, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2022, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2022, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2022, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2022, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2022, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2022, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2022, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2022, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2022, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2022, 'BELFORT', 'POLIGNY');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2023, 'BILBAO', 'BILBAO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2023, 'VITORIA-GASTEIZ', 'SAN SEBASTIÁN');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2023, 'AMOREBIETA-ETXANO', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2023, 'DAX', 'BAYONNE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2023, 'PAU', 'NOGARO');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2023, 'TARBES', 'LARUNS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2023, 'MONT-DE-MARSIN', 'CAUTARETS-CAMBASQUE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2023, 'LIBOURNE', 'BORDÉUS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2023, 'SAINT-LÉONARD-DE-NOBLAT', 'LIMOGES');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2023, 'VULCANIA', 'PUY DE DÔME');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2023, 'CLERMONT-FERRAND', 'ISSOIRE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2023, 'ROANNE', 'MOULINS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2023, 'CHÂTILLON-SUR-CHALARONNE', 'BELLEVILLE-EN-BEAUJOLAIS');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2023, 'ANNEMASSE', 'GRAND COLOMBIER');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2023, 'LES GETS', 'MORZINE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2023, 'PASSY', 'SAINT-GERVAIS MONT BLANC');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2023, 'SAINT-GERVAIS MONT BLANC', 'COMBLOUX');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2023, 'MOÛTIERS', 'COURCHEVEL');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2023, 'MOIRANS-EN-MONTAGNE', 'BOURG-EN-BRESSE');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2023, 'BELFORT', 'POLIGNY');
