insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (0, 2010, 'Viseu', 'Viseu');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (1, 2010, 'Miranda do Corvo', 'Leiria');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (2, 2010, 'Marinha Grande', 'Loures');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (3, 2010, 'Santarém', 'Castelo Branco');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (4, 2010, 'Pampilhosa da Serra', 'Covilhã');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (5, 2010, 'Oliveira do Hospital', 'Guarda');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (6, 2010, 'Torre de Moncorvo', 'Bragança');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (7, 2010, 'Bragança', 'Montalegre');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (8, 2010, 'Viana do Castelo', 'Felgueiras');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (9, 2010, 'Fafe', 'Mondim de Basto');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (10, 2010, 'Vila Nova de Gaia', 'Porto');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (11, 2010, 'Miranda do Corvo', 'Leiria');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (12, 2010, 'Marinha Grande', 'Loures');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (13, 2010, 'Santarém', 'Castelo Branco');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (14, 2010, 'Pampilhosa da Serra', 'Covilhã');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (15, 2010, 'Oliveira do Hospital', 'Guarda');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (16, 2010, 'Torre de Moncorvo', 'Bragança');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (17, 2010, 'Bragança', 'Montalegre');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (18, 2010, 'Viana do Castelo', 'Felgueiras');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (19, 2010, 'Fafe', 'Mondim de Basto');
insert into etapa (numEtapa, anoEtapa, loc_partida, loc_chegada) values (20, 2010, 'Vila Nova de Gaia', 'Porto');