insert into Movimentos (tipo) values ('Posicao');
insert into Movimentos (tipo) values ('Km prova');
insert into Movimentos (tipo) values ('Elevacao prova');
insert into Movimentos (tipo) values ('Tempo prova');
insert into Movimentos (tipo) values ('Velocidade maxima');
insert into Movimentos (tipo) values ('Velocidade media');
insert into Movimentos (tipo) values ('Calorias');
insert into Movimentos (tipo) values ('Ritmo cardiaco maximo');
insert into Movimentos (tipo) values ('Ritmo cardiaco medio');
insert into Movimentos (tipo) values ('Sprints ganhos');
insert into Movimentos (tipo) values ('Montanhas ganhas');
